version: '3'

services:
  web:
    image: nginx:latest
    ports:
       - "80:80"
       - "3000:443"
    volumes:
       - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
       - "../:/var/www/html"
    depends_on:
       - php
       - mysqldb
       - redis
  php:
    build:
       context: "./"
       dockerfile: "./php/Dockerfile"
    ports:
       - "9000"
    volumes:
       - "../:/var/www/html"
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
       - "81:80"
    environment:
       - PMA_ARBITRARY=1
       - PMA_HOST=mysqldb
    restart: always
    depends_on:
       - mysqldb
  mysqldb:
    image: mysql
    container_name: mysql
    restart: always
    env_file:
       - ".env"
    environment:
       - MYSQL_DATABASE=distribuidora
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_USER=dev
       - MYSQL_PASSWORD=dev
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
    ports:
       - "6309"
  node:
    build:
       context: "./node"
       dockerfile: "Dockerfile"
    ports:
       - "8080:8080"
    volumes:
       - "./node/home:/home"
