###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    myadmin:
      restart: always
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      ports:
          - "81:80"
      environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=mysql

    mysql:
      restart: always
      image: mysql
      container_name: dev-mysql
      environment:
          - MYSQL_DATABASE=distribuidora
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_USER=dev
          - MYSQL_PASSWORD=dev
      ports:
          - "3306:3306"
      volumes:
          - ./mysqldata:/home

    web:
      restart: always
      image: nginx:alpine
      container_name: dev-web
      working_dir: /application
      volumes:
          - ..:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"
      depends_on:
          - php-fpm

    php-fpm:
      restart: always
      build: phpdocker/php-fpm
      container_name: dev-php-fpm
      working_dir: /application
      volumes:
        - ..:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.0/fpm/conf.d/99-overrides.ini
      depends_on:
          - mysql

    node:
      restart: always
      container_name: dev-node
      build:
        context: "../"
        dockerfile: "docker/node/Dockerfile"
      ports:
         - "8080:8080"
      volumes:
         - "../:/home"

    redis:
      restart: always
      image: redis:alpine
      container_name: dev-redis

    memcached:
      restart: always
      image: memcached:alpine
      container_name: dev-memcached

